// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuKH4hqhwe_Hhj_s3f9nvhl2Mg4n0LCQk',
    appId: '1:1016878610852:web:d062516424276add436931',
    messagingSenderId: '1016878610852',
    projectId: 'encrypt-health-center-5ad3f',
    authDomain: 'encrypt-health-center-5ad3f.firebaseapp.com',
    storageBucket: 'encrypt-health-center-5ad3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6kODgKSsAlcCDDtuIo3EojSAzSbm5LDo',
    appId: '1:1016878610852:android:9de2fe4f9e5cb2e2436931',
    messagingSenderId: '1016878610852',
    projectId: 'encrypt-health-center-5ad3f',
    storageBucket: 'encrypt-health-center-5ad3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx6sRzHzPZKJwAqZ0IZJjHGLEjjprvUZ0',
    appId: '1:1016878610852:ios:e2e7b0cbd241f215436931',
    messagingSenderId: '1016878610852',
    projectId: 'encrypt-health-center-5ad3f',
    storageBucket: 'encrypt-health-center-5ad3f.firebasestorage.app',
    iosBundleId: 'com.example.eh',
  );
}
